version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb+srv://cristiaansantacruz:65673891sc@cluster1.xdzmd.mongodb.net/essiet?retryWrites=true&w=majority&appName=Cluster1"
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
